# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/kagaya85"

[social.params]
icon = "brand-github"
newtab = true

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/kagaya_85"

[social.params]
icon = "brand-twitter"
newtab = true

[[social]]
identifier = "bangumi"
name = "Bangumi"
url = "https://bangumi.tv/user/kagaya85"

[social.params]
icon = "tv"
newtab = true